package UtilisateurPane.LoginPane;

import java.net.URL;
import java.util.ResourceBundle;

import CRUD.EtabCRUD;
import CRUD.UtilisateurCRUD;
import Main.MainController;
import Modele.Etab;
import Modele.Utilisateur;
import THIS_APPLICATION.Loaded;
import UTILS.JfxUtils;
import UTILS.UTILS;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Hyperlink;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.input.KeyCode;
import javafx.scene.input.KeyEvent;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public abstract  class LoginPaneController extends StackPane implements Initializable {
	@FXML
	private ComboBox<String> comboUtilisateur;
	@FXML
	private PasswordField txtPassword;
	@FXML
	private Hyperlink btnPasswordOublie;
	@FXML
	private Button btnConnexion;
	@FXML
	private Button btnExit;
	@FXML
	private Label lblMessage;
	public static Utilisateur utilisateur=new Utilisateur();

	// Event Listener on Button[#btnPasswordOublie].onAction
	@FXML
	public void passwordOublie(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnConnexion].onAction
	@FXML
	public void connexion(ActionEvent event) {
		lblMessage.setText("");

		Utilisateur user = UtilisateurCRUD.getUtilisateur(txtPassword.getText(),
				comboUtilisateur.getSelectionModel().getSelectedItem().toString());

		if (user == null || user.getIdUtilisateur()==0) {
			lblMessage.setText("كلمة السر أو اسم المستخدم خاطئين");
		} else {

 			// do what you have to do
 			utilisateur = user; 

				logged();
			
		}
	}

	public  abstract void logged()  ;
	// Event Listener on Button[#btnExit].onAction
	@FXML
	public void exit(ActionEvent event) {

		System.exit(0);
	}

	public LoginPaneController() {
		JfxUtils.setAll("/UtilisateurPane/LoginPane/LoginPane.fxml", this);
 	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		txtPassword.setOnKeyReleased(new EventHandler<KeyEvent>() {

			@Override
			public void handle(KeyEvent arg0) {

				if (arg0.getCode() == KeyCode.ENTER) {
					connexion(null);
				}
			}

		});
		comboUtilisateur.setOnKeyReleased(new EventHandler<KeyEvent>() {

			@Override
			public void handle(KeyEvent arg0) {

				if (arg0.getCode() == KeyCode.ENTER) {
					txtPassword.requestFocus();
				}
			}

		});
		comboUtilisateur.getItems().add("a");
		comboUtilisateur.getSelectionModel().selectFirst();
	}
}
