package Modele1;
// Generated 28-Jul-2018 13:51:06 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "article", catalog = "lightstock")
public class Article implements java.io.Serializable {

	private Integer idArticle;
	private Categorie categorie;
	private String ref;
	private String description;
	private double prixAchat;
	private double prixVente;
	private double ancienPrix;
	private String codeBar;
	private String imageUrl;
	private boolean ld;
	private Double seuilAlerte;
	private double qte;
	private Set<Cmdarticlef> cmdarticlefs = new HashSet<Cmdarticlef>(0);
	private Set<Cmdarticle> cmdarticles = new HashSet<Cmdarticle>(0);

	public Article() {
	}

	public Article(String ref, String description, double prixAchat, double prixVente, double ancienPrix, boolean ld,
			double qte) {
		this.ref = ref;
		this.description = description;
		this.prixAchat = prixAchat;
		this.prixVente = prixVente;
		this.ancienPrix = ancienPrix;
		this.ld = ld;
		this.qte = qte;
	}

	public Article(Categorie categorie, String ref, String description, double prixAchat, double prixVente,
			double ancienPrix, String codeBar, String imageUrl, boolean ld, Double seuilAlerte, double qte,
			Set<Cmdarticlef> cmdarticlefs, Set<Cmdarticle> cmdarticles) {
		this.categorie = categorie;
		this.ref = ref;
		this.description = description;
		this.prixAchat = prixAchat;
		this.prixVente = prixVente;
		this.ancienPrix = ancienPrix;
		this.codeBar = codeBar;
		this.imageUrl = imageUrl;
		this.ld = ld;
		this.seuilAlerte = seuilAlerte;
		this.qte = qte;
		this.cmdarticlefs = cmdarticlefs;
		this.cmdarticles = cmdarticles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idArticle", unique = true, nullable = false)
	public Integer getIdArticle() {
		return this.idArticle;
	}

	public void setIdArticle(Integer idArticle) {
		this.idArticle = idArticle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCategorie")
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@Column(name = "ref", nullable = false)
	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "prixAchat", nullable = false, precision = 22, scale = 0)
	public double getPrixAchat() {
		return this.prixAchat;
	}

	public void setPrixAchat(double prixAchat) {
		this.prixAchat = prixAchat;
	}

	@Column(name = "prixVente", nullable = false, precision = 22, scale = 0)
	public double getPrixVente() {
		return this.prixVente;
	}

	public void setPrixVente(double prixVente) {
		this.prixVente = prixVente;
	}

	@Column(name = "ancienPrix", nullable = false, precision = 22, scale = 0)
	public double getAncienPrix() {
		return this.ancienPrix;
	}

	public void setAncienPrix(double ancienPrix) {
		this.ancienPrix = ancienPrix;
	}

	@Column(name = "codeBar")
	public String getCodeBar() {
		return this.codeBar;
	}

	public void setCodeBar(String codeBar) {
		this.codeBar = codeBar;
	}

	@Column(name = "imageURL", length = 512)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "ld", nullable = false)
	public boolean isLd() {
		return this.ld;
	}

	public void setLd(boolean ld) {
		this.ld = ld;
	}

	@Column(name = "seuilAlerte", precision = 22, scale = 0)
	public Double getSeuilAlerte() {
		return this.seuilAlerte;
	}

	public void setSeuilAlerte(Double seuilAlerte) {
		this.seuilAlerte = seuilAlerte;
	}

	@Column(name = "qte", nullable = false, precision = 22, scale = 0)
	public double getQte() {
		return this.qte;
	}

	public void setQte(double qte) {
		this.qte = qte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "article")
	public Set<Cmdarticlef> getCmdarticlefs() {
		return this.cmdarticlefs;
	}

	public void setCmdarticlefs(Set<Cmdarticlef> cmdarticlefs) {
		this.cmdarticlefs = cmdarticlefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "article")
	public Set<Cmdarticle> getCmdarticles() {
		return this.cmdarticles;
	}

	public void setCmdarticles(Set<Cmdarticle> cmdarticles) {
		this.cmdarticles = cmdarticles;
	}

}
