package Modele1;
// Generated 28-Jul-2018 13:51:06 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cmd generated by hbm2java
 */
@Entity
@Table(name = "cmd", catalog = "lightstock")
public class Cmd implements java.io.Serializable {

	private Integer idCmd;
	private Client client;
	private Utilisateur utilisateur;
	private Date date;
	private double totalCmd;
	private double totalRemise;
	private double versement;
	private boolean ld;
	private Set<Cmdarticle> cmdarticles = new HashSet<Cmdarticle>(0);

	public Cmd() {
	}

	public Cmd(double totalCmd, double totalRemise, double versement, boolean ld) {
		this.totalCmd = totalCmd;
		this.totalRemise = totalRemise;
		this.versement = versement;
		this.ld = ld;
	}

	public Cmd(Client client, Utilisateur utilisateur, Date date, double totalCmd, double totalRemise, double versement,
			boolean ld, Set<Cmdarticle> cmdarticles) {
		this.client = client;
		this.utilisateur = utilisateur;
		this.date = date;
		this.totalCmd = totalCmd;
		this.totalRemise = totalRemise;
		this.versement = versement;
		this.ld = ld;
		this.cmdarticles = cmdarticles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCmd", unique = true, nullable = false)
	public Integer getIdCmd() {
		return this.idCmd;
	}

	public void setIdCmd(Integer idCmd) {
		this.idCmd = idCmd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idClient")
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUtilisateur")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "totalCmd", nullable = false, precision = 22, scale = 0)
	public double getTotalCmd() {
		return this.totalCmd;
	}

	public void setTotalCmd(double totalCmd) {
		this.totalCmd = totalCmd;
	}

	@Column(name = "totalRemise", nullable = false, precision = 22, scale = 0)
	public double getTotalRemise() {
		return this.totalRemise;
	}

	public void setTotalRemise(double totalRemise) {
		this.totalRemise = totalRemise;
	}

	@Column(name = "versement", nullable = false, precision = 22, scale = 0)
	public double getVersement() {
		return this.versement;
	}

	public void setVersement(double versement) {
		this.versement = versement;
	}

	@Column(name = "ld", nullable = false)
	public boolean isLd() {
		return this.ld;
	}

	public void setLd(boolean ld) {
		this.ld = ld;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cmd")
	public Set<Cmdarticle> getCmdarticles() {
		return this.cmdarticles;
	}

	public void setCmdarticles(Set<Cmdarticle> cmdarticles) {
		this.cmdarticles = cmdarticles;
	}

}
