package Modele1;
// Generated 28-Jul-2018 13:51:06 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cmdf generated by hbm2java
 */
@Entity
@Table(name = "cmdf", catalog = "lightstock")
public class Cmdf implements java.io.Serializable {

	private Integer idCmdF;
	private Fournisseur fournisseur;
	private Utilisateur utilisateur;
	private Date date;
	private double totalCmd;
	private double totalRemise;
	private double versement;
	private String observation;
	private boolean ld;
	private Set<Cmdarticlef> cmdarticlefs = new HashSet<Cmdarticlef>(0);

	public Cmdf() {
	}

	public Cmdf(double totalCmd, double totalRemise, double versement, boolean ld) {
		this.totalCmd = totalCmd;
		this.totalRemise = totalRemise;
		this.versement = versement;
		this.ld = ld;
	}

	public Cmdf(Fournisseur fournisseur, Utilisateur utilisateur, Date date, double totalCmd, double totalRemise,
			double versement, String observation, boolean ld, Set<Cmdarticlef> cmdarticlefs) {
		this.fournisseur = fournisseur;
		this.utilisateur = utilisateur;
		this.date = date;
		this.totalCmd = totalCmd;
		this.totalRemise = totalRemise;
		this.versement = versement;
		this.observation = observation;
		this.ld = ld;
		this.cmdarticlefs = cmdarticlefs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCmdF", unique = true, nullable = false)
	public Integer getIdCmdF() {
		return this.idCmdF;
	}

	public void setIdCmdF(Integer idCmdF) {
		this.idCmdF = idCmdF;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFournisseur")
	public Fournisseur getFournisseur() {
		return this.fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUtilisateur")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "totalCmd", nullable = false, precision = 22, scale = 0)
	public double getTotalCmd() {
		return this.totalCmd;
	}

	public void setTotalCmd(double totalCmd) {
		this.totalCmd = totalCmd;
	}

	@Column(name = "totalRemise", nullable = false, precision = 22, scale = 0)
	public double getTotalRemise() {
		return this.totalRemise;
	}

	public void setTotalRemise(double totalRemise) {
		this.totalRemise = totalRemise;
	}

	@Column(name = "versement", nullable = false, precision = 22, scale = 0)
	public double getVersement() {
		return this.versement;
	}

	public void setVersement(double versement) {
		this.versement = versement;
	}

	@Column(name = "observation", length = 512)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Column(name = "ld", nullable = false)
	public boolean isLd() {
		return this.ld;
	}

	public void setLd(boolean ld) {
		this.ld = ld;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cmdf")
	public Set<Cmdarticlef> getCmdarticlefs() {
		return this.cmdarticlefs;
	}

	public void setCmdarticlefs(Set<Cmdarticlef> cmdarticlefs) {
		this.cmdarticlefs = cmdarticlefs;
	}

}
