package Modele1;
// Generated 28-Jul-2018 13:51:06 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "lightstock")
public class Utilisateur implements java.io.Serializable {

	private Integer idUtilisateur;
	private String nom;
	private String email;
	private String username;
	private String password;
	private String imageurl;
	private String nomAr;
	private String prenomAr;
	private Set<Cmd> cmds = new HashSet<Cmd>(0);
	private Set<Cmdf> cmdfs = new HashSet<Cmdf>(0);

	public Utilisateur() {
	}

	public Utilisateur(String nom, String email, String username, String password, String imageurl, String nomAr,
			String prenomAr) {
		this.nom = nom;
		this.email = email;
		this.username = username;
		this.password = password;
		this.imageurl = imageurl;
		this.nomAr = nomAr;
		this.prenomAr = prenomAr;
	}

	public Utilisateur(String nom, String email, String username, String password, String imageurl, String nomAr,
			String prenomAr, Set<Cmd> cmds, Set<Cmdf> cmdfs) {
		this.nom = nom;
		this.email = email;
		this.username = username;
		this.password = password;
		this.imageurl = imageurl;
		this.nomAr = nomAr;
		this.prenomAr = prenomAr;
		this.cmds = cmds;
		this.cmdfs = cmdfs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idUtilisateur", unique = true, nullable = false)
	public Integer getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "imageurl", nullable = false, length = 512)
	public String getImageurl() {
		return this.imageurl;
	}

	public void setImageurl(String imageurl) {
		this.imageurl = imageurl;
	}

	@Column(name = "nomAr", nullable = false, length = 64)
	public String getNomAr() {
		return this.nomAr;
	}

	public void setNomAr(String nomAr) {
		this.nomAr = nomAr;
	}

	@Column(name = "PrenomAr", nullable = false, length = 64)
	public String getPrenomAr() {
		return this.prenomAr;
	}

	public void setPrenomAr(String prenomAr) {
		this.prenomAr = prenomAr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Cmd> getCmds() {
		return this.cmds;
	}

	public void setCmds(Set<Cmd> cmds) {
		this.cmds = cmds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Cmdf> getCmdfs() {
		return this.cmdfs;
	}

	public void setCmdfs(Set<Cmdf> cmdfs) {
		this.cmdfs = cmdfs;
	}

}
