package UTILS.Traduction;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.Icon;

import UTILS.UTILS;

import com.mysql.jdbc.PreparedStatement;

 
public class G {

	public static final int FRANCAIS = 0;
	public static final int ARABE = 1;
	public static final int ANGLAIS = 2;
	public static final String ADRESSE = translate("ADRESSE");
	public static final String CODE_BARRE = translate("CODE BARRE");
	public static final String EMAIL = translate("EMAIL");
	public static final String TELEPHONE = translate("TÉLÉPHONE");
	public static final String RAISON_SOCIALE = translate("RAISON SOCIALE");
	public static final String RECHERCHER = translate("RECHERCHER");
	public static final String DATE_NAISSANCE = translate("DATE DE NAISSANCE");
	public static final String NOM = translate("NOM");
	public static final String PRENOM = translate("PRÉNOM");
	public static final String DATE_DECES = translate("DATE DÉCÈS");
	public static final String NUMERO = translate("NUMERO");
	public static final String AJOUTER = translate("AJOUTER");
	public static final String SUPPRIMER = translate("SUPPRIMER");
	public static final String MODIFIER = translate("MODIFIER");
	public static final String AFFICHER = translate("AFFICHER");
	public static final String COMMANDER = translate("COMMANDER");
	public static final String IMPRIMER_CARTE = translate("IMPRIMER CARTE");
	public static final String DATE_EXPIRATION = translate("DATE D'EXPIRATION");
	public static final String DATE_COMMANDE = translate("DATE COMMANDE");
	public static final String ID = translate("ID");
	public static final String QUANTITE_COMMANDE = translate("QUANTITÉ COMMANDÉE");
	public static final String PRIX_D_ACHAT = translate("PRIX D'ACHAT");
	public static final String ARTICLE = translate("ARTICLE");
	public static final String FOURNISSEUR = translate("FOURNISSEUR");
	public static final String VALIDER = translate("VALIDER");
	public static final String AJOUTER_UN_FOURNISSEUR = translate("AJOUTER UN FOURNISSEUR");
	public static final String MODIFIER_UN_FOURNISSEUR = translate("MODIFIER UN FOURNISSEUR");
	public static final String ANNULER = translate("ANNULER");
	public static final String ACTIVITE = translate("ACTIVITÉ");
	public static final String RESPONSABLE = translate("RESPONSABLE");
	public static final String PRIX = translate("PRIX");
	public static final String QUANTITE = translate("QUANTITÉ");
	public static final String NOUVEAU_FOURNISSEUR = translate("NOUVEAU FOURNISSEUR");
	public static final String FERMER = translate("FERMER");
	public static final String CHERCHER_FOURNISSEUR = translate("CHERCHER FOURNISSEUR");
	public static final String CLIENT = translate("CLIENT");
	public static final String TOTAL = translate("TOTAL");
	public static final String REFERENCE = translate("RÉFÉRENCE");
	public static final String CREER_UNE_NOUVELLE_COMMANDE = translate("CRÉER UNE NOUVELLE COMMANDE");
	public static final String VERSER = translate("VERSER");
	public static final String FAIRE_UN_VERSEMENT = translate("FAIRE UN VERSEMENT");
	public static final String CODE_PRELEVEMENT = translate("CODE PRÉLÈVEMENT");
	public static final String DATE = translate("DATE");
	public static final String MONTANT = translate("MONTANT");
	public static final String ORDRE = translate("ORDRE");
	public static final String REGLE = translate("REGLÉ");
	public static final String FAIT = translate("FAIT");
	public static final String CODE_COMMANDE = translate("CODE COMMANDE");
	public static final String TOTAL_QUANTITE = translate("TOTAL QUANTITÉ");
	public static final String TOUS = translate("TOUS");
	public static final String VERSEMENT = translate("VERSEMENT");
	public static final String VERSEMENT_INITIALE = translate("VERSEMENT INITIAL");
	public static final String AVANCEE = translate("AVANCEE");
	public static final String COMMANDE = translate("COMMANDE");
	public static final String REGLEMENT = translate("RÉGLEMENT");
	public static final String PRELEVEMENT = translate("PRELEVEMENT");
	public static final String Accueil = translate("Accueil");
	public static final String PAYEMENT = translate("Paiement");
	public static final String COMMANDES = translate("COMMANDES");
	public static final String Adherants = translate("Adhérents");
	public static final String FOURNISSEURS = translate("FOURNISSEURS");
	public static final String ARTICLES = translate("ARTICLES");
	public static final String COMMANDES_FOURNISSEURS = translate("COMMANDES FOURNISSEURS");
	public static final String RECHERCHE_AVANCEE = translate("RECHERCHE AVANCÉE");
	public static final String IMPRIMER = translate("IMPRIMER");
	public static final String MONTANT_A_PRELEVE = translate("MONTANT A PRELEVER");
	public static final String NON_FAIT = translate("NON FAIT");
	public static final String NOM_DE_UTILISATEUR = translate("NOM D'UTILISATEUR");
	public static final String NUMERO_ASSURANCE = translate("NUMERO D'ASSURANCE");
	public static final String LIEU_RESIDENCE = translate("LIEU DE RESIDENCE");
	public static final String SEXE = translate("SEXE");
	public static final String WILAYA_DE_NAISSANCE = translate("WILAYA DE NAISSANCE");
	public static final String LIEU_DE_NAISSANCE = translate("LIEU DE NAISSANCE");
	public static final String NOM_UTILISATEUR = translate("NOM D'UTILISATEUR");
	public static final String PERE = translate("PÈRE");
	public static final String MERE = translate("MÈRE");
	public static final String DECES = translate("DÉCÈS");
	public static final String RETRAITE = translate("RETRAITE");
	public static final String FIXE = translate("FIXE");
	public static final String RIB = translate("RIB");
	public static final String SOLDE_DE_DEPART = translate("SOLDE DE DÉPART");
	public static final String NUMERO_DU_DOSSIER = translate("NUMÉRO DU DOSSIER");
	public static final String BANQUE = translate("BANQUE");
	public static final String NUMERO_CCP = translate("NUMÉRO CCP");
	public static final String COMPTE_CCP = translate("COMPTE CCP");
	public static final String ADHERENT = translate("ADHÉRENT");
	public static final String ARTICLES_COMMANDES = translate("ARTICLES COMMANDÉS");
	public static final String NOUVELLE_COMMANDE = translate("NOUVELLE COMMANDE");
	public static final String NOUVEAU_ADHERANT = translate("NOUVEAU ADHÉRENT");
	public static final String NOUVEAU_ARTICLE = translate("NOUVEL ARTICLE");
	public static final String NOMBRE = translate("NOMBRE");
	public static final String MOT_DE_PASSE = translate("MOT DE PASSE");
	public static final String NUMERO_REGISTRE = translate("NUMERO REGISTRE");
	public static final String TEST = translate("TEST");
	public static final String CHARGER = translate("CHARGER");
	public static final String CLE = translate("CLÉ");
	public static final String ETAT_FOURNISSEUR = translate("ÉTAT FOURNISSEUR");
	public static final String CODE = translate("CODE");
	public static final String REALISER_COMMANDE = translate("FAITE COMMANDE");
	public static final String MOIS = translate("MOIS");
	public static final String ARTICLES_LIVRES = translate("ARTICLES LIVRÉS");
	public static final String TOTAL_PRELEVEMENTS = translate("TOTAL PRÉLÈVEMENTS");
	public static final String TOTAL_DES_ACHATS = translate("TOTAL DES ACHATS");
	public static final String TOTAL_DES_ENGAGEMENTS = translate("TOTAL DES ENGAGEMENTS");
	public static final String AFFICHER_LE_HISTORIQUE = translate("AFFICHER L'HISTORIQUE");
	public static final String HISTORIQUE = translate("HISTORIQUE");
	public static final String UTILISATEUR = translate("UTILISATEUR");
	public static final String Utilisateurs = translate("Utilisateurs");
	public static final String CONNEXION = translate("CONNEXION");
	public static final String CONFIRMER_MOT_DE_PASSE = translate("CONFIRMER MOT DE PASSE");
	public static final String FAIBLE = translate("FAIBLE");
	public static final String TRES_FORT = translate("TRÈS FORT");
	public static final String FORT = translate("FORT");
	public static final String MOYEN = translate("MOYEN");
	public static final String TRES_FAIBLE = translate("TRÈS FAIBLE");
	public static final String LISTE_PRELEVE = translate("LISTES PRÉLÈVEMENTS");
	public static final String BALAYAGE = translate("BALAYAGE");
	public static final String DATE_FIN = translate("DATE FIN");
	public static final String DATE_DEBUT = translate("DATE DEBUT");
	public static final String NOMBRE_MENSUALITE = translate("NOMBRE MENSUALITÉS");
	public static final String CCP = translate("CCP");
	public static final String EXPORTER = translate("EXPORTER");
	public static final String AJOUTER_ARTICLE = translate("AJOUTER UN ARTICLE");
	public static final String ENREGISTRER = translate("ENREGISTRER");
	public static final String LIVRER = translate("LIVRER");
	public static final String NET_A_PAYER = translate("NET À PAYER");
	public static final String IMPRIMER_BON_LIVRAISON = translate("IMPRIMER BON LIVRAISON");
	public static final String PLAN_DU_PAYEMENT = translate("PLAN DU PAIEMENT");
	public static final String MOTIF = translate("MOTIF");
	public static final String INFORMATIONS_DE_LA_COMMANDE = translate("Informations de la Commande");
	public static final String Nouvelle_Commande___ = translate("[Nouvelle Commande]");
	public static final String ETAT = translate("ÉTAT");
	public static final String NON_LIVRE = translate("NON LIVRÉ");
	public static final String LIVRE = translate("LIVRÉ");
	public static final String AJOUTER_L_ADHERANT = translate("AJOUTER L'ADHÉRENT");
	public static final String EFFACER = translate("EFFACER");
	public static final String TOTAL_DES_VERSEMENT = translate("TOTAL DES VERSEMENTS");
	public static final String RESTE_A_PAYER = translate("RESTE À PAYER");
	public static final String CHERCHER = translate("CHERCHER");
	public static final String NOUVEAU_CLIENT = translate("NOUVEAU CLIENT");
	public static final String TROUVER_CLIENT = translate("TROUVER UN CLIENT");
	public static final String IMPRIMER_LA_CARTE = translate("IMPRIMER LA CARTE");
	public static final String IMPRIMER_NOUVELLE_CARTE = translate("IMPRIMER NOUVELLE CARTE");
	public static final String IMPRIMER_LA_CARTE_ACTUEL = translate("IMPRIMER LA CARTE  ACTUELLE");
	public static final String NOUVELLE_CARTE = translate("NOUVELLE CARTE");
	public static final String CARTE_ACTUEL = translate("CARTE ACTUELLE");
	public static final String CONFIRMER = translate("CONFIRMER");
	public static final String Changer_Mot_De_Passe = translate("Changer mot de passe");
	public static final String Deconnexion = translate("Déconnexion");
	public static final String PRELEVES = translate("PRELEVES");//
	public static final String ACTUALISER = translate("ACTUALISER");
	public static final String JOUR = translate("JOUR");
	public static final String MENSUALITE = translate("MENSUALITÉ");
	public static final String LES_FICHIER_IMPORTES = translate("FICHIERS IMPORTÉS");
	public static final String DETAIL_DES_PRELEVES = translate("DÉTAIL DES PRÉLÈVEMENTS");
	public static final String ARTICLE_QTE = translate("Article/Qté");
	public static final String Informations_du_client = translate("Informations du client");
	public static final String PORTABLE = translate("PORTABLE");
	public static final String INITIALE = translate("INITIALE");
	public static final String _3_JOUR = translate("3 Jours");
	public static final String _1_semaine = translate("1 Semaine");
	public static final String _1_mois = translate("1 Mois");
	public static final String choisirer_une_fonction = translate("choisir une fonction");
	public static final String non_modifie = translate("non  modifié(e)");
	public static final String DATE_INSCRIPTION = translate("Date d'inscription");
	public static final String DATE_MODIFICATION = translate("Date modification");
	public static final String fermuture = translate("Fermeture");
	public static final String DESIGNATION = translate("DESIGNATION");
	public static final String A_PRELEVER = translate("À PRELEVER");
	public static final String RESTE = translate("RESTE");
	public static final String IMPRIMER_FICHE_INSCRIPTION = translate("IMPRIMER FICHE INSCRIPTION");
	public static final String NOUVEAU_BALAYAGE = translate("Nouveau Balayage");
	public static final String IMPORTER = translate("IMPORTER");
	public static final String TOTAL_MONTANT = translate("MONTANT TOTAL");
	public static final String NOUVEAU_LISTE_PRELEVEMENT = translate("NOUVELLE LISTE PRÉLÈVEMENTS");
	public static final String ID_FISCALE = translate("ID FISCALE");
	public static final String ENVOYER = translate("ENVOYER");
	public static final String EXIT = translate("EXIT");
	public static final String Systeme_d_exploitation = translate("Système d'exploitation");
	public static final String TAPEZ_VOTRE_MAIL_ICI = translate("TAPEZ VOTRE EMAIL ICI");
	public static final String QUITTER = translate("QUITTER");
	public static final String NUMERO_DOSSIER = translate("NUMERO DOSSIER");
	public static final String IMPRIMER_BON_COMMANDE = translate("IMPRIMER BON COMMANDE");
	public static final String APPORT_INITIALE = translate("APPORT INITIALE");
	public static final String General = translate("General");
	public static final String Image = translate("Image");
	public static final String DERNIER_QTE_COMMANDE = translate("DERNIER QTE COMMANDE");
	public static final String Ancienne = translate("Ancienne");
	public static final String total_ligne_endommage = translate("TOTAL LIGNES ENDOMMAGEES");
	public static final String Recuperation_mot_de_passe = translate("Recuperation mot de passe");
	public static final String CODE_ARTICLE = translate("code article");
	public static final String codes_barres = translate("codes barres");
	public static final String reference_fournisseur = translate("reference fournisseur");
	public static final String code_compta = translate("code compta");
	public static final String categorie = translate("categorie");
	public static final String prix_achat = translate("prix achat");
	public static final String prix_vente = translate("prix vente");
	public static final String taux_TVA = translate("taux TVA");
	public static final String prix_vente_TTC = translate("prix vente TTC");
	public static final String unite = translate("unite");
	public static final String article_gere_en_stock = translate("article gere en stock");
	public static final String quantite_en_stock = translate("quantite en stock");
	public static final String seuil_d_alerte = translate("seuil d'alerte");
	public static final String de_marge = translate("de marge");
	public static final String parcourir = translate("parcourir");
	public static final String BALAYAGES_EXPORTES = translate("LES BALAYAGES EXPORTEES");
	public static final String LES_BALAYAGE = translate("LES BALAYAGE");
	public static final String Gestion_des_OS_Bejaia = translate("Gestion des OS-Bejaia");
	public static final String changer_image_fond_ecran = translate("Changer image fond écran");
	public static final String Statistique = translate("Statistique");
	public static final String Vente_du_dernier_7_jours = translate("Vente du dernier 7 jours");
	public static final String JOURS = translate("JOURS");
	public static final String Vente_Da = translate("Vente(Da)");
	public static final String francais = translate("Fran\u00E7ais");
	public static final String anglais = translate("Anglais");
	public static final String arabe = translate("Arabe");
	public static final String INFOS_COMMANDE_ = translate("INFOS COMMANDE : ");
	public static final String AJOUTER_UN_UTILISATEUR = translate("AJOUTER UN UTILISATEUR");
	public static final String MODIFIER_UN_UTILISATEUR = translate("MODIFIER UN UTILISATEUR");
	public static final String Droit_Acces = translate("Droit Acces");
	public static final String autorisation = translate("Autorisation");
	public static final String Generer_un_mot_de_passe = translate("Generer un mot de passe");
	public static final String date_modification = translate("Date modification");
	public static final String date_Inscription = translate("Date Inscription");
	public static final String LES_DROITS_D_ACCES = translate("LES DROITS D'ACCÉS");
	public static final String MODIFIER_L_ADHERANT = translate("MODIFIER L'ADHERANT");
	public static final String dernier_Mise_a_jour = translate("dernier Mise a jour");
	public static final String article_desactive = translate("Article Desactivé");
	public static final String AJOUTER_NOUVEAU_ARTICLE = translate("AJOUTER NOUVEAU ARTICLE");
	public static final String l_article = translate("L'article ");
	public static final String ENDROIT = translate("ENDROIT");
	public static final String DATE_CREATION = translate("DATE CREATION");
	public static final String CATEGORIE = translate("CATEGORIE");
	public static final String ETABLISSMENT = translate("Établissment");
	public static final String REUNION = translate("REUNION");
	public static final String choisir_un_etablissement = translate("choisir un établissement");
	public static final String AJOUTER_UN_ETABLISSEMENT = translate("AJOUTER UN ETABLISSEMENT");
	public static final String MODIFIER_UN_ETABLISSEMENT = translate("MODIFIER UN ETABLISSEMENT");
	public static final String Contenu = translate("CONTENU");
	public static final String TITRE = translate("TITRE");
	public static final String PRESIDENT = translate("PRESIDENT");
	public static final String PRESENCE_REUNION = translate("PRESENCE REUNION");
	public static final String STATUS = translate("STATUS");
	public static final String REPRESENTANT = translate("REPRESENTANT");
	public static final String NOMBRE_ENSEIGNANTS = translate("NOMBRE D'ENSEIGNANTS");
	public static final String AJOUTER_UNE_REUNION = translate("AJOUTER UNE REUNION");
	public static final String MODIFIER_LA_REUNION = translate("MODIFIER LA REUNION");
	public static final String MEMBRES_REUNION = translate("MEMBRES REUNION");
	public static final String IMPRIMER_LA_LISTE_DES_MEMBRES_DU_REUNION = translate("IMPRIMER LA LISTE DES MEMBRES DU REUNION");
	public static final String IMPRIMER_LISTE_REPRESENTANTS_PRESENTS = translate("IMPRIMER LISTE REPRESENTANTS PRESENTS");
	public static final String IMPRIMER_LISTE_REPRESENTANTS_ABSENTS = translate("IMPRIMER LISTE REPRESENTANTS ABSENTS");
	public static final String Bienvenue = translate("Bienvenue");
	public static final String TOTAL_PRESENCE = translate("TOTAL PRESENCE");
	public static final String NOM_EN_ARABE = translate("NOM EN ARABE");
	public static final String Gestion_des_Reunions_Bejaia = translate("Gestion des Reunions Bejaia");
	public static final String PHOTO = translate("PHOTO");
	public static final String LABEL = translate("LABEL");
	public static final String MENU = translate("MENU");
	public static final String CAPTURE_ECRAN = translate("CAPTURE ECRAN");
	public static final String NON = translate("NON");
	public static final String D_accord = translate("D'ACCORD");
	public static final String OUI = translate("OUI");
	public static final String choisirer_le_role = translate("CHOISIRER LE ROLE");
	public static final String AJOUTER_AUTOMATIQUEMENT = translate("AJOUTER AUTOMATIQUEMENT");
	public static final String erreur_inconnu = translate("erreur inconnu");
	public static final String choisir_une_categorie = translate("choisir une categorie");
	public static final String version_enregistree = translate("version enregistrée");
	public static final String version_non_enregistree = translate("version non enregistrée");
	public static final String erreur = translate("erreur");
	public static final String Entrer__ = translate("Entrer..");
	public static final String Message = translate("Message");
	public static final String corbeille = translate("corbeille");
	public static final String VOLUME_SONS = translate("VOLUME SONS");
	public static final String filtrage_impression_carte = translate("filtrage carte");
	public static final String carte_imprime = translate("carte imprimé");
	public static final String carte_non_imprime = translate("carte non imprimé");
	public static final String Camera = translate("Camera");
	public static final String Demarrer = translate("Démarrer");
	public static final String Prendre_une_photo = translate("Prendre une photo");
	public static final String Ressayer = translate("Ressayer");
	public static final String Parametrage = translate("Parametrage");
	public static final String CARTE = translate("CARTE");
	public static final String DATE_DELIBERATION = translate("DATE  DÉLIBÉRATION");
	public static final String IMPRIMER_LA_LISTE_DES_MEMBRES_DU_DELIBERATION = translate("IMPRIMER LA LISTE DES MEMBRES DU DELIBERATION");
	public static final String AJOUTER_A_LA_DELIBERATION = translate("AJOUTER A LA DÉLIBÉRATION");
	public static final String Deliberations = translate("Délibérations");
	public static final String IMPRIMER_LISTE_MEMBRES_PRESENTS = translate("IMPRIMER LISTE MEMBRES PRESENTS");
	public static final String IMPRIMER_LISTE_MEMBRES_ABSENTS = translate("IMPRIMER LISTE MEMBRES ABSENTS");
	public static final String PRESTATION = translate("PRESTATION");
	public static final String MODIFIER_UNE_PRESTATION = translate("MODIFIER UNE PRESTATION");
	public static final String AJOUTER_UNE_PRESTATION = translate("AJOUTER UN PRESTATION");
	public static final String TYPE = translate("TYPE");
	public static final String  ACTIVE = translate("ACTIVE");
	public static final String DETAIL = translate("DETAIL");
	public static final String ECHEANCEE = translate("ECHEANCEE");
	public static final String Dossier_Administrative = translate("Dossier Administrative");
	public static final String NOUVELLE_PRESTATION = translate("NOUVELLE PRESTATION");
	public static final String CHERCHER_PRESTATION = translate("CHERCHER PRESTATION");
	public static final String OBSERVATION = translate("OBSERVATION");
	public static final String SERVICE_CLIENT = translate("SERVICE CLIENT");
	public static final String OK = translate("OK");
	public static final String AIDE = translate("AIDE");
	public static final String PRET = translate("PRET");
	public static final String NON_TRAITES = translate("NON TRAITES");
	public static final String ACCEPTE = translate("ACCEPTE");
	public static final String REFUSE = translate("REFUSE");
	public static final String DECISION_DE_LA_COMMISSION = translate("DECISION DE LA COMMISSION");
	public static final String Les_ayants_droit = translate("LES AYANTS DROIT");
	public static final String Ayants_droit = translate("Ayants droit");
	public static final String LIEN_PARENTAL = translate("LIEN PARENTAL");
	public static final String LES_AYANTS_DROITS = translate("LES AYANTS DROITS");
	public static final String NOUVEAU_AYANT_DROIT = translate("NOUVEAU AYANT DROIT");
	public static final String FRERE = translate("FRERE");
	public static final String FILS = translate("FILS");
	public static final String AUCUNE = translate("AUCUNE");
	public static final String HUSBAND = translate("HUSBAND");
	public static final String RELATION = translate("RELATION");
	public static final String FEMININ = translate("Féminin");
	public static final String MASCULIN = translate("Masculin");
	public static final String AUCUN_CLIENT = translate("Aucun client");
	public static final String AJOUTER_AYANT_DROIT = translate("AJOUTER AYANT DROIT");
	public static final String MODIFIER_AYANT_DROIT = translate("MODIFIER AYANT DROIT");
	public static final String PROFESSION = translate("PROFESSION");
	public static final String LES_CARTES = translate("LES CARTES");
	public static final String LES_PROFESSIONS = translate("PROFESSIONS");
	public static final String AUCUNE_PRESTATION = translate("AUCUNE PRESTATION");
	public static final String Demande_prestation = translate("Demande prestation");
	public static final String SELECTIONNER_TOUT = translate("SÉLECTIONNER TOUT");
	public static final String DECISION = translate("DECISION");
	public static final String PRESTATION_AR = translate("PRESTATION AR");
	public static final String AYANT_DROIT_INTERESSE = translate("AYANTS DROITS INTERESSES");
	public static final String RESTAURER = translate("RESTAURER");
	public static final String NOM_DEPOT = translate("NOM DERPOT");
	public static final String FAX = translate("FAX");
	public static final String NOM_RESPONSABLE = translate("NOM RESPONSABLE");
	public static final String NOM_LIVREUR = translate("NOM LIVREUR");
	public static final String SUPERFICIE = translate("SUPERFICIE");
	public static final String MAX_LIVRAISON = translate("MAX LIVRAISON");
	public static final String PAYE = translate("PAYE");
	public static final String CARTE_LIVRE = translate("CARTE LIVRE");
	public static final String Objectif = translate("Objectif");
	public static final String Le_membre_n_a_ete_ajoute = translate("Le membre n'a été ajouté");
	public static final String Informations_de_base = translate("Informations de base");
	public static final String Conditions = translate("Conditions");
	public static final String MEMBRES_DELIBERATION = translate("MEMBRES DÉLIBÉRATION");
	public static final String PRESENCE_DELIBERATION = translate("PRESENCE DÉLIBÉRATION");
	public static final String MODIFIER_LA_DELIBERATION = translate("MODIFIER LA DELIBERATION");
	public static final String DELIBERATION = translate("DÉLIBÉRATION");
	public static final String AJOUTER_UNE_DELIBERATION = translate("AJOUTER UNE DÉLIBÉRATION");
	public static final String CHERCHER_DELIBERATION = translate("CHERCHER DÉLIBÉRATION");
	public static final String NOUVEAU_DEMANDE_PRESTATION = translate("NOUVEAU DEMANDE PRESTATION");
	public static final String POURCENTAGE = translate("POURCENTAGE");
	public static final String MONTANT_D_AIDE = translate("MONTANT D'AIDE");
	public static final String REFUSER = translate("REFUSER");
	public static final String ACCEPTER = translate("ACCEPTER");
	public static final String NOMBRE_AIDE = translate("NOMBRE AIDE");
	public static final String NOMBRE_PRET = translate("NOMBRE PRET");
	public static final String MONTANT_AIDE = translate("MONTANT AIDE");
	public static final String MONTANT_PRET = translate("MONTANT PRET");
	public static final String DELIBERER = translate("DELIBERER");
	public static final String IMPORTER_NOUVEAU = translate("IMPORTER NOUVEAU");
	public static final String CREER_UN_NOUVEAU_BALAYAGE = translate("CREER UN NOUVEAU BALAYAGE");
	public static final String NON_DELEBERE = translate("NON DELEBERE");
	public static final String DELIBERE_LE = translate("DELIBERE LE");
	public static final String ROLE_MEMBRES_REUNION = translate("RÔLES MEMBRES RÉUNION");
	public static final String HISTORIQUE_VENTE_CLIENT = translate("HISTORIQUE VENTE(CLIENT)");
	public static final String AFFICHER_LE_HISTORIQUE_PRESTATION = translate("AFFICHER LE HISTORIQUE PRESTATION");
	public static final String HISTORIQUE_PRESTATION = translate("HISTORIQUE PRESTATION");
	public static final String AUCUN_PERSONNE = translate("AUCUN PERSONNE");
	public static final String CLOTURE_DU_DELIBERATION = translate("CLOTURE DU DÉLIBÉRATION");
	public static final String DEMANDES_DELIBERES = translate("DEMANDES DELIBERES");
	public static final String DOCUMENT = translate("DOCUMENT");
	public static final String EXPIRATION = translate("EXPIRATION");
	public static final String DUREE_D_EXPIRATION = translate("DUREE D'EXPIRATION");
	public static final String AJOUTER_UN_DOCUMENT = translate("AJOUTER UN DOCUMENT");
	public static final String MODIFIER_UN_DOCUMENT = translate("MODIFIER UN DOCUMENT");
	public static final String CHERCHER_DOCUMENT = translate("CHERCHER DOCUMENT");
	public static final String DUREE_D_VALIDITE = translate("DUREE DE VALIDITE");
	public static final String NOUVEAU_DOCUMENT = translate("NOUVEAU DOCUMENT");
	public static final String NOMBRE_DES_COPIES = translate("NOMBRE DES COPIES");
	public static final String TYPE_DOCUMENT = translate("TYPE DOCUMENT");
	public static final String AUTRES = translate("AUTRES");
	public static final String TYPES_DES_DOCUMENTS = translate("TYPES DES DOCUMENTS");
	public static final String Liste_des_documents = translate("Liste des documents");
	public static final String DOCUMENT_AR_ = translate("DOCUMENT(AR)");
	public static final String GESTION_DES_DOCUMENTS = translate("GESTION DES DOCUMENTS");
	public static final String DOCUMENTS = translate("DOCUMENTS");
	public static final String Ouvrir_le_dossier = translate("Ouvrir le dossier");
	public static final String Afficher_les_documents_requis = translate("Afficher les documents requis");
	public static final String CIVILITES = translate("CIVILITÉS");
	public static final String INSTANCE = translate("INSTANCE");
	public static final String DELIBERE = translate("DELIBERÉ");
	public static final String Prestations =translate("Prestations");
	public static final String LIENS_PARENTAL = translate("LIENS PARENTAL");
	public static final String NON_DEFINI = translate("NON DEFINI");
	public static final String Nombre_des_adherents_selon_sexe = translate("le nombre des adhérents selon le sexe");
	public static final String Sexe = translate("Sexe");
	public static final String Adherents_sans_Carte = translate("Adherents sans Carte");
	public static final String Adherents_avec_Carte = translate("Adherents avec Carte");
	public static final String Nombre_des_adherents_selon_Impression_Carte = translate("Nombre des adherents selon Impression Carte");
	public static final String Nombre_des_demandes_services_selon_decision = translate("Nombre des demandes services selon les décisions");
	public static final String Nombre_demandes = translate("Nombre demandes");
	public static final String DECISIONS = translate("DECISIONS");
	public static final String Demandes_acceptes = translate("Les demandes acceptés");
	public static final String Demandes_refusees = translate("Demandes refusées");
	public static final String Demandes_en_instance = translate("Demandes en instance");
	public static final String Demandes_non_etudies = translate("Demandes non étudiées");
	public static final String En_instance = translate("En instance");
	public static final String  Acceptees = translate("Acceptées");
	public static final String NON_ETUDIEES = translate("Non étudiées");
	public static final String Derniere_deliberation = translate("La dernière délibération");
	public static final String FILE_D_ATTENTE = translate("File d'attente");
	public static final String Future_deliberation = translate("FUTURE DÉLIBÉRATION");
	public static final String Derniere_deliberation_AIDE_PRET = translate("La dernière délibération (AIDE/PRET)");
	public static final String Future_deliberation_AIDE_PRET = translate("FUTURE DÉLIBÉRATION (AIDE-PRET)");
	public static final String Montant_future_deliberation_AIDE_PRET = translate("Montant de LA FUTURE DÉLIBÉRATION (AIDE-PRET)");
	public static final String Montant_la_derniere_deliberation_AIDE_PRET = translate("Montant de la dernière délibération (AIDE-PRET)");
	public static final String Statistiques = translate("Statistiques");
	public static final String Minimum = translate("Minimum");
	public static final String Maximum = translate("Maximum");
	public static final String POINT_INTERROGATION__ = translate(" ?");
	public static final String TOUT_DELIBERATIONS = translate("TOUT DELIBERATIONS");
	public static final String TOUT_PRESTATIONS = translate("TOUT PRESTATIONS");
	public static final String TOUT_CLIENT = translate("TOUT CLIENT");
	public static final String Demandes = translate("Demandes");
	public static final String DEMANDE_PRESTATION = translate("DEMANDE PRESTATION");
	public static final String CHAPITRE = translate("CHAPITRE");
	public static final String CHAPITRE_AR = translate("CHAPITRE AR");
	public static final String AJOUTER_UN_CHAPITRE = translate("AJOUTER UN CHAPITRE");
	public static final String MODIFIER_UN_CHAPITRE = translate("MODIFIER UN CHAPITRE");
	public static final String ANNEE = translate("ANNEE");
	public static final String VERS_LE_CHAPITRE = translate("VERS LE CHAPITRE");
	public static final String NOUVEAU_CHAPITRE = translate("NOUVEAU CHAPITRE");
	public static final String Chapitres = translate("Chapitres");
	public static final String Credit_Initial = translate("Credit initial");
	public static final String Transfert_credit = translate("Transfert credit");
	public static final String ENTREE = translate("ENTREE");
	public static final String SORTIE = translate("SORTIE");
	public static final String AUCUN_CHAPITRE = translate("AUCUN CHAPITRE");
	public static final String LES_ETABLISSMENTS = translate("LES ETABLISSMENTS");
	public static final String PRIMAIRE = translate("PRIMAIRE");
	public static final String CEM = translate("CEM");
	public static final String LYCEE = translate("LYCÉE");
	public static final String AUCUN = translate("AUCUN");
	public static final String JOURNAL = translate("JOURNAL");
	public static final String PC = translate("PC");
	public static final String IP = translate("IP");
	public static final String NOUVEAU_UTILISATEUR = translate("NOUVEAU UTILISATEUR");
	public static final String TROUVER__ = translate("TROUVER ...");
	public static final String TACHE = translate("Tache");
	public static final String Operation = translate("Operation");
	public static final String WILAYA = translate("Wilaya");
	public static final String Daira = translate("Daira");
	public static final String Commune = translate("Commune");
	public static final String NOUVEAU_ETABLISSEMENT = translate("NOUVEAU ETABLISSEMENT");
	public static final String AUCUNE_ETABLISSEMENT = translate("AUCUNE ETABLISSEMENT");
	public static final String NUMERO_INSCRIPTION_SYNDICAT_ = translate("NUMERO D'INSCRIPTION(SYNDICAT)");
	public static final String Filtrer_par_sexe = translate("Filtrer par sexe");
	public static final String CIVILITE = translate("Civilité");
	public static final String Assistant_pour_preciser_le = translate("Assistant pour preciser le sexe des personnes");
	public static final String Date_inscription = translate("Date inscription");
	public static final String Latine = translate("Latine");
	public static final String Liste_des_etablissement = translate("Liste des établissement");
	public static final String LOCALISATION = translate("LOCALISATION");
	public static final String Selectionner_un_chapitre_ici = translate("Selectionner un chapitre ici");
	public static final String BILAN = translate("Bilan");
	public static final String Configuration_du_serveur = translate("Configuration du serveur");
	public static final String Port = translate("Port");
	public static final String Serveur = translate("Serveur");
	public static final String Base_de_donnees = translate("Base de données");
	public static final String Dossier = translate("Dossier");
	public static final String Longeur_des_mot_de_passe_generes = translate("Longeur des mot de passe générés");
	public static final String COMMISSION_PRESENT_A_LA_DELIBERATION = translate("COMMISSION PRESENT A LA DELIBERATION");
	public static final String NAISSANCE = translate("NAISSANCE");
	public static final String PV = translate("PV");
	public static final String NOMBRE_PRESENCE_PV = translate("NOMBRE PRESENCE PV");
	
	public static String LE_MEMBRE=translate("LE MEMBRE");
	public static String de =translate("de");
	public static String a=translate("a");
	public static String sujet=translate("sujet");
	public static String fichier_attache=translate("fichier attache");
	public static String ouvrir=translate("ouvrir");
	public static String fichier_introuvable__=translate("fichier introuvable");
	public static String service_mail=translate("Service mail");
	public static String en_cours_d_envoi=translate("en cours d'envoi");
	public static String copie_s_=translate("copie(s)");
	public static String  Visualiser_le_dossier=translate("Visualiser le dossier");
	public static String Refusees=translate("Refusées");
	public static String ETUDIEES=translate("Étudiées");
	public static String demande_s_=translate(" demande(s)?");
	public static String Liste_des_adherents=translate("Liste des adherents");
	public static String temporaire_stockage_photos=translate("temporaire stockage photos");
	public static String n_carte=translate("N° Carte");
	public static String a_ete_modifie="تم التعديل بنجاح";
	public static String il_y_a_un_erreur="حدث خطأ ما";
	public static String un_erreur="خطأ";
	public static String fait_="تم " ;
	public static String article_a_ete_ajoute="تم اضافة  التعيين  بنجاح";
	public static String client_a_ete_ajoute="تم اضافة الزبون  بنجاح";
	public static String a_ete_supprime="تم الحذف بنجاح";
	public static String fournisseur_a_ete_ajoute="تم اضافة الممون  بنجاح";
	
	
	
	public  static String translate(String string) {
		// TODO Auto-generated method stub
		return "fffffffffffffffffffffkdf,sf54s5df456sdd";
	}


//	static final String translate(String WORD) {
//		if (Parameter.LANGUE == FRANCAIS) {
//			return WORD;
//		}
//		String language = null;
//		if (Parameter.LANGUE == ARABE) {
//			language = "Ar";
//		}
//		if (Parameter.LANGUE == ANGLAIS) {
//			language = "Ang";
//		}
//
//		try {
//			String requete = "select * from glossaire where Fr=?";
//
//			java.sql.PreparedStatement ps = ConnectionDB.getCon()
//					.prepareStatement(requete);
//			ps.setNString(1, WORD);
//			ResultSet rs = ps.executeQuery();
//			System.out.println(requete);
//			if (rs.next()) {
//				return rs.getNString(language);
//			} else {
//				ajouterGlossaire(WORD);
//			}
//		} catch (SQLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//		return WORD;
//	}
//
//	public static final int ajouterGlossaire(String mot_fr) {
//		String requete = "INSERT INTO glossaire( Fr, Ar, Ang) VALUES (?,?,?)";
//		try {
//			java.sql.PreparedStatement ps = ConnectionDB.getCon()
//					.prepareStatement(requete,
//							PreparedStatement.RETURN_GENERATED_KEYS);
//			ps.setNString(1, mot_fr);
//			ps.setNString(2, "");
//			ps.setNString(3, "");
//			ps.executeUpdate();
//			return UTILS.getLastGeneratedID(ps);
//		} catch (SQLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//		return -1;
//	}

}
