package Modele;
// Generated 8 juil. 2018 03:27:56 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie", catalog = "lightstock")
public class Categorie implements java.io.Serializable {

	private Integer idCategorie;
	private String nomCategorie;
	private boolean ld;
	private Set<Article> articles = new HashSet<Article>(0);

	public Categorie() {
	}

	public Categorie(String nomCategorie, boolean ld) {
		this.nomCategorie = nomCategorie;
		this.ld = ld;
	}

	public Categorie(String nomCategorie, boolean ld, Set<Article> articles) {
		this.nomCategorie = nomCategorie;
		this.ld = ld;
		this.articles = articles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCategorie", unique = true, nullable = false)
	public Integer getIdCategorie() {
		return this.idCategorie;
	}

	public void setIdCategorie(Integer idCategorie) {
		this.idCategorie = idCategorie;
	}

	@Column(name = "nomCategorie", nullable = false)
	public String getNomCategorie() {
		return this.nomCategorie;
	}

	public void setNomCategorie(String nomCategorie) {
		this.nomCategorie = nomCategorie;
	}

	@Column(name = "ld", nullable = false)
	public boolean isLd() {
		return this.ld;
	}

	public void setLd(boolean ld) {
		this.ld = ld;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
