package Modele;
// Generated 8 juil. 2018 03:27:56 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Cmdarticle generated by hbm2java
 */
@Entity
@Table(name = "cmdarticle", catalog = "lightstock")
public class Cmdarticle implements java.io.Serializable {

	private Integer idCmdArticle;
	private Article article;
	private Cmd cmd;
	private double qte;
	private double prix;
	private double prixVente;
	private int ordre;

	public Cmdarticle() {
	}

	public Cmdarticle(Article article, Cmd cmd, double qte, double prix, double prixVente, int ordre) {
		this.article = article;
		this.cmd = cmd;
		this.qte = qte;
		this.prix = prix;
		this.prixVente = prixVente;
		this.ordre = ordre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCmdArticle", unique = true, nullable = false)
	public Integer getIdCmdArticle() {
		return this.idCmdArticle;
	}

	public void setIdCmdArticle(Integer idCmdArticle) {
		this.idCmdArticle = idCmdArticle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idArticle", nullable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCmd", nullable = false)
	public Cmd getCmd() {
		return this.cmd;
	}

	public void setCmd(Cmd cmd) {
		this.cmd = cmd;
	}

	@Column(name = "qte", nullable = false, precision = 22, scale = 0)
	public double getQte() {
		return this.qte;
	}

	public void setQte(double qte) {
		this.qte = qte;
	}

	@Column(name = "prix", nullable = false, precision = 22, scale = 0)
	public double getPrix() {
		return this.prix;
	}

	public void setPrix(double prix) {
		this.prix = prix;
	}

	@Column(name = "prixVente", nullable = false, precision = 22, scale = 0)
	public double getPrixVente() {
		return this.prixVente;
	}

	public void setPrixVente(double prixVente) {
		this.prixVente = prixVente;
	}

	@Column(name = "ordre", nullable = false)
	public int getOrdre() {
		return this.ordre;
	}

	public void setOrdre(int ordre) {
		this.ordre = ordre;
	}

	@Transient
	public String getRef() {
		return article.getRef();
	}

	@Transient
	public double getPrixVenteTotal() {
		return qte * prixVente;
	}

	@Transient
	public Integer getIdArticle() {
		return article.getIdArticle();
	}

	@Override
	public boolean equals(Object obj) {
		// TODO Auto-generated method stub
		return getIdCmdArticle()==((Cmdarticle)obj).getIdCmdArticle();
	}
	
}
