package Modele;
// Generated 18-Jul-2018 17:24:08 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Etab generated by hbm2java
 */
@Entity
@Table(name = "etab", catalog = "lightstock")
public class Etab implements java.io.Serializable {

	private int idEtab;
	private String nom;
	private String title;
	private String description;
	private String faita;
	private String email;
	private String password;
	private String port;
	private String serveurSmtp;
	private String tel;
	private String siteWeb;
	private String adresse;
	private boolean ld;
	private String slogan;
	private String urlLogo;
	private String repEntete;

	public Etab() {
	}

	public Etab(int idEtab, String email, String password, String port, String serveurSmtp, String tel, boolean ld,
			String repEntete) {
		this.idEtab = idEtab;
		this.email = email;
		this.password = password;
		this.port = port;
		this.serveurSmtp = serveurSmtp;
		this.tel = tel;
		this.ld = ld;
		this.repEntete = repEntete;
	}

	public Etab(int idEtab, String nom, String title, String description, String faita, String email, String password,
			String port, String serveurSmtp, String tel, String siteWeb, String adresse, boolean ld, String slogan,
			String urlLogo, String repEntete) {
		this.idEtab = idEtab;
		this.nom = nom;
		this.title = title;
		this.description = description;
		this.faita = faita;
		this.email = email;
		this.password = password;
		this.port = port;
		this.serveurSmtp = serveurSmtp;
		this.tel = tel;
		this.siteWeb = siteWeb;
		this.adresse = adresse;
		this.ld = ld;
		this.slogan = slogan;
		this.urlLogo = urlLogo;
		this.repEntete = repEntete;
	}

	@Id

	@Column(name = "idEtab", unique = true, nullable = false)
	public int getIdEtab() {
		return this.idEtab;
	}

	public void setIdEtab(int idEtab) {
		this.idEtab = idEtab;
	}

	@Column(name = "nom", length = 512)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "title", length = 512)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "faita", length = 55)
	public String getFaita() {
		return this.faita;
	}

	public void setFaita(String faita) {
		this.faita = faita;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "port", nullable = false)
	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	@Column(name = "serveurSMTP", nullable = false)
	public String getServeurSmtp() {
		return this.serveurSmtp;
	}

	public void setServeurSmtp(String serveurSmtp) {
		this.serveurSmtp = serveurSmtp;
	}

	@Column(name = "tel", nullable = false)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "siteWeb")
	public String getSiteWeb() {
		return this.siteWeb;
	}

	public void setSiteWeb(String siteWeb) {
		this.siteWeb = siteWeb;
	}

	@Column(name = "adresse", length = 512)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "ld", nullable = false)
	public boolean isLd() {
		return this.ld;
	}

	public void setLd(boolean ld) {
		this.ld = ld;
	}

	@Column(name = "slogan", length = 512)
	public String getSlogan() {
		return this.slogan;
	}

	public void setSlogan(String slogan) {
		this.slogan = slogan;
	}

	@Column(name = "urlLogo", length = 1024)
	public String getUrlLogo() {
		return this.urlLogo;
	}

	public void setUrlLogo(String urlLogo) {
		this.urlLogo = urlLogo;
	}

	@Column(name = "rep_entete", nullable = false, length = 1024)
	public String getRepEntete() {
		return this.repEntete;
	}

	public void setRepEntete(String repEntete) {
		this.repEntete = repEntete;
	}

}
